# Generated by Django 4.2.4 on 2023-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto_vendido',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='ejecutivo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.JSONField(default=list),
        ),
    ]
