# Generated by Django 4.2.4 on 2023-11-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_producto_vendido_venta_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='stock_entregado',
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.JSONField(default={'cantidad': 0, 'id': 0, 'nombre': '', 'precio': 0.0}),
        ),
    ]
